// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_stage4_beatmasters = "CgkIhuD7vY4CEAIQEQ"; // <GPGSID>
        public const string achievement_first_one_star = "CgkIhuD7vY4CEAIQBw"; // <GPGSID>
        public const string achievement_purchase_crown_item = "CgkIhuD7vY4CEAIQBg"; // <GPGSID>
        public const string achievement_grown = "CgkIhuD7vY4CEAIQCA"; // <GPGSID>
        public const string leaderboard_stage1_beatmasters = "CgkIhuD7vY4CEAIQDg"; // <GPGSID>
        public const string leaderboard_stage2_beatmasters = "CgkIhuD7vY4CEAIQDw"; // <GPGSID>
        public const string achievement_purchase_first_item = "CgkIhuD7vY4CEAIQBQ"; // <GPGSID>
        public const string leaderboard_stage3_beatmasters = "CgkIhuD7vY4CEAIQEA"; // <GPGSID>
        public const string achievement_first_payment = "CgkIhuD7vY4CEAIQCw"; // <GPGSID>
        public const string achievement_master = "CgkIhuD7vY4CEAIQCQ"; // <GPGSID>
        public const string achievement_clear_once = "CgkIhuD7vY4CEAIQDA"; // <GPGSID>
        public const string achievement_purchase_first_character = "CgkIhuD7vY4CEAIQBA"; // <GPGSID>
        public const string achievement_clear_10_times = "CgkIhuD7vY4CEAIQDQ"; // <GPGSID>
        public const string achievement_restart_over_hundred = "CgkIhuD7vY4CEAIQCg"; // <GPGSID>

}

